use master;

CREATE DATABASE SoftUni;
use SoftUni;

CREATE TABLE Towns (
Id INT PRIMARY KEY IDENTITY,
Name VARCHAR(30) NOT NULL
);

CREATE TABLE Addresses (
Id INT PRIMARY KEY IDENTITY,
AddressText VARCHAR(50) NOT NULL,
TownId INT FOREIGN KEY REFERENCES Towns(Id),
);


CREATE TABLE Departments (
Id INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(30) NOT NULL
);

CREATE TABLE Employees (
Id INT PRIMARY KEY IDENTITY,
FirstName NVARCHAR(20) NOT NULL,
MiddleName NVARCHAR(20),
LastName NVARCHAR(20) NOT NULL,
JobTitle VARCHAR(30),
DepartmentId INT FOREIGN KEY REFERENCES Departments(Id),
HireDate DATE NOT NULL,
Salary DECIMAL(8,2),
AddressId INT FOREIGN KEY REFERENCES Addresses(Id)
);